---
title: "Statistical and Causal Inference"
author: "Johannes Textor"
date: "`r Sys.Date()`"
output:
  bookdown::gitbook: default
  bookdown::pdf_book:
    latex_engine: xelatex
knitr:
  opts_chunk:
    warning: false
    message: false
---

# Introduction {-}

Welcome to the transcripts for the course "Statistical and causal inference"!

These transcripts are generated by combining an AI-generated transcript of the lecture recordings with the lecture notes (Markdown file I'm using during the lecture itself). I edit these by hand --- I've tried to use AI for this but it doesn't work well.

Initially, I only lightly edited the transcripts --- trying to keep as much as possible of what was being said --- but upon some feedback, the later chapters are edited more heavily, and I may also sometimes decide to omit things that were said in the lecture (such as purely organizational matters that are not relevant beyond the week in question). Therefore, you will see the style shift from the earlier to the later chapters.

If you spot any error in this transcript (that isn't just a trivial typo), you can send it to me and I will count it for your Portfolio item 1.

## Generative AI disclosure {-}

The initial version of the transcripts are generated by OpenAI Whisper (running locally) from the lecture recording. 

I edit the transcripts by hand, without the use of AI. (I tried a few times to get Claude Sonnet 4.5 or ChatGPT 5 to help me, but it didn't work so well, and I ended up using none of this help.) 

I use Claude Sonnet 4.5 to proofread the transcript and identify any errors or typos. I fix these errors myself by hand.

I use Claude Sonnet 4.5 to help generate the formative questions at the end of each lecture, in the following way. Once I am done with editing the transcript, I ask Claude to generate about twice as many questions as I am aiming for. I then delete all questions that I find too boring, to vague, or not well suited for testing the content, and edit the other questions to my liking. I then add additional questions by hand if I feel the difficulty level is not well balanced or a certain topic is not covered enough.
